Version 2.1.0
microsoft/webvalidate pull request #24
Opened 2021-07-24 05:48 UTC by bartr

# Type of PR

- [x] Documentation changes
- [x] Code changes
- [x] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## Purpose of PR

- bug fixes
- add support for xunit test output

2021-07-27 18:23 UTC, joheec requested changes
Rebase

2021-07-28 13:59 UTC, sivamu reviewed
Changes look good, and got to try the code out within codespaces, which worked pretty well. One small thing I noticed was I couldn't get the summary type none to work, passing the value and via the default:
![image](https://user-images.githubusercontent.com/67930841/127335337-0a198026-4015-448b-9838-56008da5c99c.png)

2021-07-29 02:39 UTC, joheec approved these changes

2021-07-29 02:41 UTC, joheec approved these changes

2021-07-29 02:47 UTC, merged